name: Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build 
      
